// src/services/mockData.ts

import type { Document } from '@/types/document.types';

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: '1',
    id_l: 1,
    processo_s: '10580.123456/2024-01',
    tipo_processo_s: 'LANÇAMENTO',
    subtipo_processo_s: 'AUTO DE INFRAÇÃO',
    grupo_processo_s: 'PROCESSO TRIBUTÁRIO',
    nome_arquivo_s: 'auto_infracao_001.pdf',
    titulo_s: 'Auto de Infração - IRPJ 2023',
    tipo_documento_s: 'AUTO DE INFRAÇÃO',
    situacao_s: 'JUNTADO',
    tamanho_l: 2048576,
    dt_juntada_tdt: '2024-01-15T10:30:00Z',
    dt_protocolo_tdt: '2024-01-10T14:20:00Z',
    dt_registro_tdt: '2024-01-15T10:35:00Z',
    dt_anexacao_tdt: '2024-01-14T16:45:00Z',
    atualizado_anexos_dt: '2024-01-15T10:35:00Z',
    nome_contribuinte_s: 'EMPRESA EXEMPLO LTDA',
    ni_contribuinte_s: '12345678000190',
    cpf_responsavel_s: '12345678901',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - SÃO PAULO',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - SÃO PAULO',
    equipe_origem_s: 'EQUIPE FISCALIZAÇÃO 01',
    nome_equipe_atual_s: 'EQUIPE FISCALIZAÇÃO 01',
    codigo_act_s: '123.456.789',
    origem_act_s: 'FISCALIZAÇÃO',
    tema_act_s: '001',
    nome_tema_act_s: 'IRPJ - Omissão de Receitas',
    tributo_act_s: 'IRPJ',
    act_s: '123',
    atividade_origem_s: 'Fiscalização IRPJ',
    assuntos_objetos_s: 'IRPJ OMISSÃO RECEITAS',
    urlHcpPrincipal_s: 'https://exemplo.com/doc1',
    urlHcpSecundario_s: 'https://exemplo.com/doc1-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Auto de infração referente ao exercício de 2023...',
    nome_usuario_juntada_doc_s: 'João Silva',
    _version_: 1,
    score: 1.5
  },
  {
    id: '2',
    id_l: 2,
    processo_s: '10580.789012/2024-02',
    tipo_processo_s: 'RESTITUIÇÃO',
    subtipo_processo_s: 'PEDIDO DE RESTITUIÇÃO',
    grupo_processo_s: 'PROCESSO TRIBUTÁRIO',
    nome_arquivo_s: 'pedido_restituicao_002.pdf',
    titulo_s: 'Pedido de Restituição - IRRF',
    tipo_documento_s: 'PETIÇÃO',
    situacao_s: 'JUNTADO',
    tamanho_l: 1024000,
    dt_juntada_tdt: '2024-02-20T09:15:00Z',
    dt_protocolo_tdt: '2024-02-18T11:00:00Z',
    dt_registro_tdt: '2024-02-20T09:20:00Z',
    dt_anexacao_tdt: '2024-02-19T15:30:00Z',
    atualizado_anexos_dt: '2024-02-20T09:20:00Z',
    nome_contribuinte_s: 'MARIA SANTOS',
    ni_contribuinte_s: '98765432000110',
    cpf_responsavel_s: '98765432100',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - RIO DE JANEIRO',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - RIO DE JANEIRO',
    equipe_origem_s: 'EQUIPE ATENDIMENTO 02',
    nome_equipe_atual_s: 'EQUIPE ATENDIMENTO 02',
    codigo_act_s: '987.654.321',
    origem_act_s: 'ATENDIMENTO',
    tema_act_s: '002',
    nome_tema_act_s: 'IRRF - Restituição',
    tributo_act_s: 'IRRF',
    act_s: '987',
    atividade_origem_s: 'Atendimento ao Contribuinte',
    assuntos_objetos_s: 'IRRF RESTITUIÇÃO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc2',
    urlHcpSecundario_s: 'https://exemplo.com/doc2-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Pedido de restituição de IRRF retido indevidamente...',
    nome_usuario_juntada_doc_s: 'Maria Oliveira',
    _version_: 1,
    score: 1.3
  },
  {
    id: '3',
    id_l: 3,
    processo_s: '10580.345678/2024-03',
    tipo_processo_s: 'RESSARCIMENTO',
    subtipo_processo_s: 'PEDIDO DE RESSARCIMENTO',
    grupo_processo_s: 'PROCESSO TRIBUTÁRIO',
    nome_arquivo_s: 'ressarcimento_003.pdf',
    titulo_s: 'Ressarcimento - PIS/COFINS',
    tipo_documento_s: 'REQUERIMENTO',
    situacao_s: 'EM ANÁLISE',
    tamanho_l: 3072000,
    dt_juntada_tdt: '2024-03-10T14:25:00Z',
    dt_protocolo_tdt: '2024-03-08T10:15:00Z',
    dt_registro_tdt: '2024-03-10T14:30:00Z',
    dt_anexacao_tdt: '2024-03-09T13:20:00Z',
    atualizado_anexos_dt: '2024-03-10T14:30:00Z',
    nome_contribuinte_s: 'INDÚSTRIA XYZ S.A.',
    ni_contribuinte_s: '11223344000155',
    cpf_responsavel_s: '11223344556',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - BRASÍLIA',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - BRASÍLIA',
    equipe_origem_s: 'EQUIPE ANÁLISE 03',
    nome_equipe_atual_s: 'EQUIPE ANÁLISE 03',
    codigo_act_s: '111.222.333',
    origem_act_s: 'RESSARCIMENTO',
    tema_act_s: '003',
    nome_tema_act_s: 'PIS/COFINS - Ressarcimento',
    tributo_act_s: 'PIS/COFINS',
    act_s: '111',
    atividade_origem_s: 'Análise de Ressarcimento',
    assuntos_objetos_s: 'PIS COFINS RESSARCIMENTO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc3',
    urlHcpSecundario_s: 'https://exemplo.com/doc3-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Pedido de ressarcimento de créditos de PIS/COFINS...',
    nome_usuario_juntada_doc_s: 'Carlos Souza',
    _version_: 1,
    score: 1.8
  },
  {
    id: '4',
    id_l: 4,
    processo_s: '13031.567890/2023-04',
    tipo_processo_s: 'OUTROS PREVIDENCIÁRIO',
    subtipo_processo_s: 'CERTIDÃO',
    grupo_processo_s: 'PROCESSO PREVIDENCIÁRIO',
    nome_arquivo_s: 'certidao_previdenciaria.pdf',
    titulo_s: 'Certidão de Regularidade Previdenciária',
    tipo_documento_s: 'CERTIDÃO',
    situacao_s: 'DEFERIDO',
    tamanho_l: 512000,
    dt_juntada_tdt: '2023-12-05T08:45:00Z',
    dt_protocolo_tdt: '2023-12-01T09:30:00Z',
    dt_registro_tdt: '2023-12-05T08:50:00Z',
    dt_anexacao_tdt: '2023-12-04T16:00:00Z',
    atualizado_anexos_dt: '2023-12-05T08:50:00Z',
    nome_contribuinte_s: 'COMÉRCIO ABC LTDA',
    ni_contribuinte_s: '55667788000199',
    cpf_responsavel_s: '55667788990',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - BELO HORIZONTE',
    nome_unidade_atual_s: 'ARQUIVO ÚNICO',
    equipe_origem_s: 'EQUIPE CERTIDÕES',
    nome_equipe_atual_s: 'ARQUIVO ÚNICO',
    codigo_act_s: '444.555.666',
    origem_act_s: 'ATENDIMENTO',
    tema_act_s: '004',
    nome_tema_act_s: 'Certidão Previdenciária',
    tributo_act_s: 'CONTRIBUIÇÃO PREVIDENCIÁRIA',
    act_s: '444',
    atividade_origem_s: 'Emissão de Certidões',
    assuntos_objetos_s: 'CERTIDÃO PREVIDÊNCIA',
    urlHcpPrincipal_s: 'https://exemplo.com/doc4',
    urlHcpSecundario_s: 'https://exemplo.com/doc4-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'S',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Certidão de regularidade fiscal previdenciária...',
    nome_usuario_juntada_doc_s: 'Ana Paula',
    _version_: 1,
    score: 1.1
  },
  {
    id: '5',
    id_l: 5,
    processo_s: '16682.901234/2024-05',
    tipo_processo_s: 'AÇÃO JUDICIAL',
    subtipo_processo_s: 'MANDADO DE SEGURANÇA',
    grupo_processo_s: 'PROCESSO ADMINISTRATIVO',
    nome_arquivo_s: 'mandado_seguranca.pdf',
    titulo_s: 'Mandado de Segurança - Suspensão de Exigibilidade',
    tipo_documento_s: 'PETIÇÃO INICIAL',
    situacao_s: 'JUNTADO',
    tamanho_l: 4096000,
    dt_juntada_tdt: '2024-01-25T11:10:00Z',
    dt_protocolo_tdt: '2024-01-22T15:45:00Z',
    dt_registro_tdt: '2024-01-25T11:15:00Z',
    dt_anexacao_tdt: '2024-01-24T10:30:00Z',
    atualizado_anexos_dt: '2024-01-25T11:15:00Z',
    nome_contribuinte_s: 'CONSTRUTORA DELTA S.A.',
    ni_contribuinte_s: '99887766000144',
    cpf_responsavel_s: '99887766554',
    unidade_origem_s: 'PROCURADORIA GERAL DA FAZENDA NACIONAL',
    nome_unidade_atual_s: 'PROCURADORIA GERAL DA FAZENDA NACIONAL',
    equipe_origem_s: 'EQUIPE JURÍDICA 01',
    nome_equipe_atual_s: 'EQUIPE JURÍDICA 01',
    codigo_act_s: '777.888.999',
    origem_act_s: 'PGFN',
    tema_act_s: '005',
    nome_tema_act_s: 'Ações Judiciais',
    tributo_act_s: 'DIVERSOS',
    act_s: '777',
    atividade_origem_s: 'Contencioso Judicial',
    assuntos_objetos_s: 'MANDADO SEGURANÇA SUSPENSÃO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc5',
    urlHcpSecundario_s: 'https://exemplo.com/doc5-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Mandado de segurança visando suspender exigibilidade...',
    nome_usuario_juntada_doc_s: 'Roberto Lima',
    _version_: 1,
    score: 2.1
  },
  {
    id: '6',
    id_l: 6,
    processo_s: '20010.111213/2024-06',
    tipo_processo_s: 'ATENDIMENTO',
    subtipo_processo_s: 'RECLAMAÇÃO',
    grupo_processo_s: 'PROCESSO ADMINISTRATIVO',
    nome_arquivo_s: 'reclamacao_006.pdf',
    titulo_s: 'Reclamação - Cobrança Indevida',
    tipo_documento_s: 'RECLAMAÇÃO',
    situacao_s: 'EM TRAMITAÇÃO',
    tamanho_l: 256000,
    dt_juntada_tdt: '2024-06-12T09:00:00Z',
    dt_protocolo_tdt: '2024-06-10T08:30:00Z',
    dt_registro_tdt: '2024-06-12T09:05:00Z',
    dt_anexacao_tdt: '2024-06-11T17:00:00Z',
    atualizado_anexos_dt: '2024-06-12T09:05:00Z',
    nome_contribuinte_s: 'JOÃO PEREIRA',
    ni_contribuinte_s: '22334455000166',
    cpf_responsavel_s: '22334455667',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - SALVADOR',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - SALVADOR',
    equipe_origem_s: 'EQUIPE ATENDIMENTO 05',
    nome_equipe_atual_s: 'EQUIPE ATENDIMENTO 05',
    codigo_act_s: '222.333.444',
    origem_act_s: 'ATENDIMENTO',
    tema_act_s: '006',
    nome_tema_act_s: 'Cobrança Indevida',
    tributo_act_s: 'DIVERSOS',
    act_s: '222',
    atividade_origem_s: 'Atendimento',
    assuntos_objetos_s: 'COBRANÇA INDEVIDA',
    urlHcpPrincipal_s: 'https://exemplo.com/doc6',
    urlHcpSecundario_s: 'https://exemplo.com/doc6-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Reclamação referente a cobrança de tributo não devido...',
    nome_usuario_juntada_doc_s: 'Marcos Tavares',
    _version_: 1,
    score: 0.9
  },
  {
    id: '7',
    id_l: 7,
    processo_s: '20011.121314/2024-07',
    tipo_processo_s: 'INSPEÇÃO',
    subtipo_processo_s: 'RELATÓRIO',
    grupo_processo_s: 'PROCESSO FISCAL',
    nome_arquivo_s: 'relatorio_inspecao_007.pdf',
    titulo_s: 'Relatório de Inspeção - Estabelecimento',
    tipo_documento_s: 'RELATÓRIO',
    situacao_s: 'FINALIZADO',
    tamanho_l: 768000,
    dt_juntada_tdt: '2024-07-03T12:00:00Z',
    dt_protocolo_tdt: '2024-07-01T10:00:00Z',
    dt_registro_tdt: '2024-07-03T12:05:00Z',
    dt_anexacao_tdt: '2024-07-02T14:15:00Z',
    atualizado_anexos_dt: '2024-07-03T12:05:00Z',
    nome_contribuinte_s: 'LOJA MODELO EIRELI',
    ni_contribuinte_s: '33445566000177',
    cpf_responsavel_s: '33445566778',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - CURITIBA',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - CURITIBA',
    equipe_origem_s: 'EQUIPE FISCALIZAÇÃO 07',
    nome_equipe_atual_s: 'EQUIPE FISCALIZAÇÃO 07',
    codigo_act_s: '333.444.555',
    origem_act_s: 'INSPEÇÃO',
    tema_act_s: '007',
    nome_tema_act_s: 'Inspeção Estabelecimento',
    tributo_act_s: 'ICMS',
    act_s: '333',
    atividade_origem_s: 'Inspeção Fiscal',
    assuntos_objetos_s: 'INSPEÇÃO ESTABELECIMENTO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc7',
    urlHcpSecundario_s: 'https://exemplo.com/doc7-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'N',
    indicador_gerado_sistema_s: 'S',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Relatório final de inspeção com constatações e autos...',
    nome_usuario_juntada_doc_s: 'Paula Ribeiro',
    _version_: 2,
    score: 1.0
  },
  {
    id: '8',
    id_l: 8,
    processo_s: '30020.314159/2023-08',
    tipo_processo_s: 'ARQUIVO',
    subtipo_processo_s: 'DOCUMENTO',
    grupo_processo_s: 'PROCESSO ADMINISTRATIVO',
    nome_arquivo_s: 'documento_008.pdf',
    titulo_s: 'Documento Avulso - Informação',
    tipo_documento_s: 'DOCUMENTO',
    situacao_s: 'ARQUIVADO',
    tamanho_l: 128000,
    dt_juntada_tdt: '2023-08-15T07:30:00Z',
    dt_protocolo_tdt: '2023-08-14T09:00:00Z',
    dt_registro_tdt: '2023-08-15T07:35:00Z',
    dt_anexacao_tdt: '2023-08-14T12:00:00Z',
    atualizado_anexos_dt: '2023-08-15T07:35:00Z',
    nome_contribuinte_s: 'ASSOCIAÇÃO CULTURAL XYZ',
    ni_contribuinte_s: '44556677000188',
    cpf_responsavel_s: '44556677889',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - PORTO ALEGRE',
    nome_unidade_atual_s: 'ARQUIVO DEPARTAMENTAL',
    equipe_origem_s: 'EQUIPE ARQUIVO',
    nome_equipe_atual_s: 'EQUIPE ARQUIVO',
    codigo_act_s: '555.666.777',
    origem_act_s: 'ARQUIVO',
    tema_act_s: '008',
    nome_tema_act_s: 'Documento Informativo',
    tributo_act_s: 'N/A',
    act_s: '555',
    atividade_origem_s: 'Arquivo',
    assuntos_objetos_s: 'DOCUMENTO AVULSO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc8',
    urlHcpSecundario_s: 'https://exemplo.com/doc8-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'N',
    indicador_original_pesquisavel_s: 'N',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'N',
    sem_conteudo_s: 'S',
    conteudo_txt: '',
    nome_usuario_juntada_doc_s: 'Arquivo Sistema',
    _version_: 1,
    score: 0.2
  },
  {
    id: '9',
    id_l: 9,
    processo_s: '40040.271828/2024-09',
    tipo_processo_s: 'DECLARAÇÃO',
    subtipo_processo_s: 'ANEXO',
    grupo_processo_s: 'PROCESSO TRIBUTÁRIO',
    nome_arquivo_s: 'declaração_009.pdf',
    titulo_s: 'Declaração de Rendimentos - Anexo',
    tipo_documento_s: 'DECLARAÇÃO',
    situacao_s: 'JUNTADO',
    tamanho_l: 640000,
    dt_juntada_tdt: '2024-09-01T10:00:00Z',
    dt_protocolo_tdt: '2024-08-30T09:45:00Z',
    dt_registro_tdt: '2024-09-01T10:05:00Z',
    dt_anexacao_tdt: '2024-08-31T12:30:00Z',
    atualizado_anexos_dt: '2024-09-01T10:05:00Z',
    nome_contribuinte_s: 'FARMÁCIA POPULAR LTDA',
    ni_contribuinte_s: '66778899000155',
    cpf_responsavel_s: '66778899166',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - FORTALEZA',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - FORTALEZA',
    equipe_origem_s: 'EQUIPE RECEBIMENTO',
    nome_equipe_atual_s: 'EQUIPE RECEBIMENTO',
    codigo_act_s: '666.777.888',
    origem_act_s: 'DECLARAÇÃO',
    tema_act_s: '009',
    nome_tema_act_s: 'Declaração de Rendimentos',
    tributo_act_s: 'IRPF',
    act_s: '666',
    atividade_origem_s: 'Recebimento Declarações',
    assuntos_objetos_s: 'DECLARAÇÃO IRPF',
    urlHcpPrincipal_s: 'https://exemplo.com/doc9',
    urlHcpSecundario_s: 'https://exemplo.com/doc9-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Declaração de rendimentos com anexos comprobatórios...',
    nome_usuario_juntada_doc_s: 'Luciana Martins',
    _version_: 1,
    score: 1.4
  },
  {
    id: '10',
    id_l: 10,
    processo_s: '50050.141421/2023-10',
    tipo_processo_s: 'NOTIFICAÇÃO',
    subtipo_processo_s: 'CARTA',
    grupo_processo_s: 'PROCESSO TRIBUTÁRIO',
    nome_arquivo_s: 'notificacao_010.pdf',
    titulo_s: 'Notificação de Lançamento',
    tipo_documento_s: 'NOTIFICAÇÃO',
    situacao_s: 'ENVIADO',
    tamanho_l: 350000,
    dt_juntada_tdt: '2023-10-20T09:30:00Z',
    dt_protocolo_tdt: '2023-10-18T08:00:00Z',
    dt_registro_tdt: '2023-10-20T09:35:00Z',
    dt_anexacao_tdt: '2023-10-19T11:30:00Z',
    atualizado_anexos_dt: '2023-10-20T09:35:00Z',
    nome_contribuinte_s: 'SERVIÇOS GAMA LTDA',
    ni_contribuinte_s: '77889900112233',
    cpf_responsavel_s: '77889900123',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - MANAUS',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - MANAUS',
    equipe_origem_s: 'EQUIPE NOTIFICAÇÕES',
    nome_equipe_atual_s: 'EQUIPE NOTIFICAÇÕES',
    codigo_act_s: '888.999.000',
    origem_act_s: 'LANÇAMENTO',
    tema_act_s: '010',
    nome_tema_act_s: 'Notificação Formal',
    tributo_act_s: 'ISS',
    act_s: '888',
    atividade_origem_s: 'Notificação',
    assuntos_objetos_s: 'NOTIFICAÇÃO LANÇAMENTO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc10',
    urlHcpSecundario_s: 'https://exemplo.com/doc10-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'N',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Notificação enviada ao contribuinte sobre débito apurado...',
    nome_usuario_juntada_doc_s: 'Fernando Costa',
    _version_: 1,
    score: 1.0
  },
  {
    id: '11',
    id_l: 11,
    processo_s: '60060.271828/2024-11',
    tipo_processo_s: 'CARTÓRIO',
    subtipo_processo_s: 'TERMO',
    grupo_processo_s: 'PROCESSO ADMINISTRATIVO',
    nome_arquivo_s: 'termo_011.pdf',
    titulo_s: 'Termo de Ciência',
    tipo_documento_s: 'TERMO',
    situacao_s: 'ASSINADO',
    tamanho_l: 1280000,
    dt_juntada_tdt: '2024-11-05T14:00:00Z',
    dt_protocolo_tdt: '2024-11-03T09:00:00Z',
    dt_registro_tdt: '2024-11-05T14:05:00Z',
    dt_anexacao_tdt: '2024-11-04T12:00:00Z',
    atualizado_anexos_dt: '2024-11-05T14:05:00Z',
    nome_contribuinte_s: 'INSTITUTO TECNOLÓGICO ABC',
    ni_contribuinte_s: '88990011223344',
    cpf_responsavel_s: '88990011234',
    unidade_origem_s: 'CARTÓRIO CENTRAL',
    nome_unidade_atual_s: 'CARTÓRIO CENTRAL',
    equipe_origem_s: 'EQUIPE CARTÓRIO',
    nome_equipe_atual_s: 'EQUIPE CARTÓRIO',
    codigo_act_s: '999.000.111',
    origem_act_s: 'CARTÓRIO',
    tema_act_s: '011',
    nome_tema_act_s: 'Termo de Ciência',
    tributo_act_s: 'N/A',
    act_s: '999',
    atividade_origem_s: 'Expedição de Termos',
    assuntos_objetos_s: 'TERMO CIÊNCIA',
    urlHcpPrincipal_s: 'https://exemplo.com/doc11',
    urlHcpSecundario_s: 'https://exemplo.com/doc11-sec',
    indicador_sigilo_s: 'S',
    indicador_pesquisavel_s: 'N',
    indicador_original_pesquisavel_s: 'N',
    indicador_gerado_sistema_s: 'S',
    arquivo_indexado_s: 'N',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Termo assinado digitalmente pelo responsável...',
    nome_usuario_juntada_doc_s: 'Cartório Sistema',
    _version_: 3,
    score: 0.7
  },
  {
    id: '12',
    id_l: 12,
    processo_s: '70070.161803/2024-12',
    tipo_processo_s: 'FISCALIZAÇÃO',
    subtipo_processo_s: 'AUTO',
    grupo_processo_s: 'PROCESSO TRIBUTÁRIO',
    nome_arquivo_s: 'auto_fiscal_012.pdf',
    titulo_s: 'Auto de Fiscalização - Multa',
    tipo_documento_s: 'AUTO',
    situacao_s: 'EM ANDAMENTO',
    tamanho_l: 1800000,
    dt_juntada_tdt: '2024-12-12T08:00:00Z',
    dt_protocolo_tdt: '2024-12-10T08:30:00Z',
    dt_registro_tdt: '2024-12-12T08:05:00Z',
    dt_anexacao_tdt: '2024-12-11T13:20:00Z',
    atualizado_anexos_dt: '2024-12-12T08:05:00Z',
    nome_contribuinte_s: 'TRANSPORTES ALFA LTDA',
    ni_contribuinte_s: '99001122334455',
    cpf_responsavel_s: '99001122345',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - SÃO LUÍS',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - SÃO LUÍS',
    equipe_origem_s: 'EQUIPE FISCALIZAÇÃO 12',
    nome_equipe_atual_s: 'EQUIPE FISCALIZAÇÃO 12',
    codigo_act_s: '101.202.303',
    origem_act_s: 'FISCALIZAÇÃO',
    tema_act_s: '012',
    nome_tema_act_s: 'Auto Fiscal',
    tributo_act_s: 'ICMS',
    act_s: '101',
    atividade_origem_s: 'Fiscalização Transporte',
    assuntos_objetos_s: 'MULTA FISCALIZAÇÃO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc12',
    urlHcpSecundario_s: 'https://exemplo.com/doc12-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Auto lavrado por infração ao ICMS no transporte de mercadorias...',
    nome_usuario_juntada_doc_s: 'Juliana Freitas',
    _version_: 1,
    score: 1.6
  },
  {
    id: '13',
    id_l: 13,
    processo_s: '80080.314159/2023-13',
    tipo_processo_s: 'COMUNICAÇÃO',
    subtipo_processo_s: 'OFÍCIO',
    grupo_processo_s: 'PROCESSO ADMINISTRATIVO',
    nome_arquivo_s: 'oficio_013.pdf',
    titulo_s: 'Ofício - Solicitação de Documentos',
    tipo_documento_s: 'OFÍCIO',
    situacao_s: 'RESPONDIDO',
    tamanho_l: 220000,
    dt_juntada_tdt: '2023-03-20T10:10:00Z',
    dt_protocolo_tdt: '2023-03-18T09:00:00Z',
    dt_registro_tdt: '2023-03-20T10:15:00Z',
    dt_anexacao_tdt: '2023-03-19T12:00:00Z',
    atualizado_anexos_dt: '2023-03-20T10:15:00Z',
    nome_contribuinte_s: 'SECRETARIA MUNICIPAL XYZ',
    ni_contribuinte_s: '11122233344455',
    cpf_responsavel_s: '11122233344',
    unidade_origem_s: 'ASSESSORIA JURÍDICA',
    nome_unidade_atual_s: 'ASSESSORIA JURÍDICA',
    equipe_origem_s: 'EQUIPE COMUNICAÇÃO',
    nome_equipe_atual_s: 'EQUIPE COMUNICAÇÃO',
    codigo_act_s: '121.212.121',
    origem_act_s: 'COMUNICAÇÃO',
    tema_act_s: '013',
    nome_tema_act_s: 'Solicitação Documentos',
    tributo_act_s: 'N/A',
    act_s: '121',
    atividade_origem_s: 'Ofícios',
    assuntos_objetos_s: 'SOLICITAÇÃO DOCUMENTOS',
    urlHcpPrincipal_s: 'https://exemplo.com/doc13',
    urlHcpSecundario_s: 'https://exemplo.com/doc13-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Ofício solicitando envio de documentação comprobatória...',
    nome_usuario_juntada_doc_s: 'André Gomes',
    _version_: 1,
    score: 0.8
  },
  {
    id: '14',
    id_l: 14,
    processo_s: '90090.161803/2024-14',
    tipo_processo_s: 'AUDITORIA',
    subtipo_processo_s: 'RELATÓRIO FINAL',
    grupo_processo_s: 'PROCESSO INTERNO',
    nome_arquivo_s: 'relatorio_auditoria_014.pdf',
    titulo_s: 'Relatório Final de Auditoria Interna',
    tipo_documento_s: 'RELATÓRIO',
    situacao_s: 'CONCLUÍDO',
    tamanho_l: 2300000,
    dt_juntada_tdt: '2024-04-25T16:00:00Z',
    dt_protocolo_tdt: '2024-04-20T09:00:00Z',
    dt_registro_tdt: '2024-04-25T16:05:00Z',
    dt_anexacao_tdt: '2024-04-24T11:10:00Z',
    atualizado_anexos_dt: '2024-04-25T16:05:00Z',
    nome_contribuinte_s: 'DIRETORIA ADMINISTRATIVA',
    ni_contribuinte_s: '00011122233344',
    cpf_responsavel_s: '00011122233',
    unidade_origem_s: 'AUDITORIA INTERNA',
    nome_unidade_atual_s: 'AUDITORIA INTERNA',
    equipe_origem_s: 'EQUIPE AUDITORIA',
    nome_equipe_atual_s: 'EQUIPE AUDITORIA',
    codigo_act_s: '131.313.131',
    origem_act_s: 'AUDITORIA',
    tema_act_s: '014',
    nome_tema_act_s: 'Auditoria Interna',
    tributo_act_s: 'N/A',
    act_s: '131',
    atividade_origem_s: 'Auditoria',
    assuntos_objetos_s: 'RELATÓRIO AUDITORIA',
    urlHcpPrincipal_s: 'https://exemplo.com/doc14',
    urlHcpSecundario_s: 'https://exemplo.com/doc14-sec',
    indicador_sigilo_s: 'S',
    indicador_pesquisavel_s: 'N',
    indicador_original_pesquisavel_s: 'N',
    indicador_gerado_sistema_s: 'S',
    arquivo_indexado_s: 'N',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Conclusões e recomendações da auditoria interna...',
    nome_usuario_juntada_doc_s: 'Equipe Auditoria',
    _version_: 2,
    score: 1.9
  },
  {
    id: '15',
    id_l: 15,
    processo_s: '10101.314159/2024-15',
    tipo_processo_s: 'CERTIFICAÇÃO',
    subtipo_processo_s: 'CERTIFICADO',
    grupo_processo_s: 'PROCESSO ADMINISTRATIVO',
    nome_arquivo_s: 'certificado_015.pdf',
    titulo_s: 'Certificado de Regularidade Fiscal',
    tipo_documento_s: 'CERTIFICADO',
    situacao_s: 'EMITIDO',
    tamanho_l: 410000,
    dt_juntada_tdt: '2024-05-10T10:10:00Z',
    dt_protocolo_tdt: '2024-05-08T09:00:00Z',
    dt_registro_tdt: '2024-05-10T10:15:00Z',
    dt_anexacao_tdt: '2024-05-09T13:00:00Z',
    atualizado_anexos_dt: '2024-05-10T10:15:00Z',
    nome_contribuinte_s: 'EMPRESA DE SERVIÇOS BETA',
    ni_contribuinte_s: '12121212000199',
    cpf_responsavel_s: '12121212001',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - GOIÂNIA',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - GOIÂNIA',
    equipe_origem_s: 'EQUIPE CERTIFICAÇÃO',
    nome_equipe_atual_s: 'EQUIPE CERTIFICAÇÃO',
    codigo_act_s: '141.414.141',
    origem_act_s: 'CERTIFICAÇÃO',
    tema_act_s: '015',
    nome_tema_act_s: 'Certificado Regularidade',
    tributo_act_s: 'N/A',
    act_s: '141',
    atividade_origem_s: 'Emissão Certificados',
    assuntos_objetos_s: 'CERTIFICADO REGULARIDADE',
    urlHcpPrincipal_s: 'https://exemplo.com/doc15',
    urlHcpSecundario_s: 'https://exemplo.com/doc15-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'S',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Certificado emitido atestando regularidade fiscal...',
    nome_usuario_juntada_doc_s: 'Equipe Certificação',
    _version_: 1,
    score: 1.2
  },
  {
    id: '16',
    id_l: 16,
    processo_s: '11111.271828/2024-16',
    tipo_processo_s: 'PLANO',
    subtipo_processo_s: 'APRESENTAÇÃO',
    grupo_processo_s: 'PROCESSO INTERNO',
    nome_arquivo_s: 'plano_trabalho_016.pdf',
    titulo_s: 'Plano de Trabalho - Projeto X',
    tipo_documento_s: 'PLANO',
    situacao_s: 'EM APROVAÇÃO',
    tamanho_l: 1400000,
    dt_juntada_tdt: '2024-06-01T09:00:00Z',
    dt_protocolo_tdt: '2024-05-30T08:00:00Z',
    dt_registro_tdt: '2024-06-01T09:05:00Z',
    dt_anexacao_tdt: '2024-05-31T15:00:00Z',
    atualizado_anexos_dt: '2024-06-01T09:05:00Z',
    nome_contribuinte_s: 'PROJETO X CORP',
    ni_contribuinte_s: '13131313000166',
    cpf_responsavel_s: '13131313130',
    unidade_origem_s: 'COORDENAÇÃO PROJETOS',
    nome_unidade_atual_s: 'COORDENAÇÃO PROJETOS',
    equipe_origem_s: 'EQUIPE PROJETOS',
    nome_equipe_atual_s: 'EQUIPE PROJETOS',
    codigo_act_s: '151.515.151',
    origem_act_s: 'PLANO',
    tema_act_s: '016',
    nome_tema_act_s: 'Plano Trabalho',
    tributo_act_s: 'N/A',
    act_s: '151',
    atividade_origem_s: 'Gestão Projetos',
    assuntos_objetos_s: 'PLANO TRABALHO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc16',
    urlHcpSecundario_s: 'https://exemplo.com/doc16-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'N',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Plano de trabalho detalhando entregas e prazos...',
    nome_usuario_juntada_doc_s: 'Coordenador Projetos',
    _version_: 1,
    score: 1.05
  },
  {
    id: '17',
    id_l: 17,
    processo_s: '12121.141421/2024-17',
    tipo_processo_s: 'REQUERIMENTO',
    subtipo_processo_s: 'ALTERAÇÃO CADASTRAL',
    grupo_processo_s: 'PROCESSO TRIBUTÁRIO',
    nome_arquivo_s: 'alteracao_cadastral_017.pdf',
    titulo_s: 'Requerimento - Alteração Cadastral',
    tipo_documento_s: 'REQUERIMENTO',
    situacao_s: 'EM PROCESSAMENTO',
    tamanho_l: 330000,
    dt_juntada_tdt: '2024-07-11T11:30:00Z',
    dt_protocolo_tdt: '2024-07-10T10:15:00Z',
    dt_registro_tdt: '2024-07-11T11:35:00Z',
    dt_anexacao_tdt: '2024-07-10T13:20:00Z',
    atualizado_anexos_dt: '2024-07-11T11:35:00Z',
    nome_contribuinte_s: 'PESSOA FÍSICA EXEMPLO',
    ni_contribuinte_s: '14141414000188',
    cpf_responsavel_s: '14141414141',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - NATAL',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - NATAL',
    equipe_origem_s: 'EQUIPE CADASTRO',
    nome_equipe_atual_s: 'EQUIPE CADASTRO',
    codigo_act_s: '161.616.161',
    origem_act_s: 'ATENDIMENTO',
    tema_act_s: '017',
    nome_tema_act_s: 'Alteração Cadastral',
    tributo_act_s: 'N/A',
    act_s: '161',
    atividade_origem_s: 'Cadastro',
    assuntos_objetos_s: 'ALTERAÇÃO CADASTRO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc17',
    urlHcpSecundario_s: 'https://exemplo.com/doc17-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Solicitação de alteração de endereço e atividade econômica...',
    nome_usuario_juntada_doc_s: 'Equipe Cadastro',
    _version_: 1,
    score: 0.95
  },
  {
    id: '18',
    id_l: 18,
    processo_s: '13131.271828/2024-18',
    tipo_processo_s: 'PAGAMENTO',
    subtipo_processo_s: 'COMPROVANTE',
    grupo_processo_s: 'PROCESSO TRIBUTÁRIO',
    nome_arquivo_s: 'comprovante_pagamento_018.pdf',
    titulo_s: 'Comprovante de Pagamento - DARF',
    tipo_documento_s: 'COMPROVANTE',
    situacao_s: 'JUNTADO',
    tamanho_l: 90000,
    dt_juntada_tdt: '2024-08-02T08:30:00Z',
    dt_protocolo_tdt: '2024-07-30T16:00:00Z',
    dt_registro_tdt: '2024-08-02T08:35:00Z',
    dt_anexacao_tdt: '2024-08-01T09:00:00Z',
    atualizado_anexos_dt: '2024-08-02T08:35:00Z',
    nome_contribuinte_s: 'PAGAMENTOS RÁPIDOS LTDA',
    ni_contribuinte_s: '15151515000111',
    cpf_responsavel_s: '15151515151',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - VITÓRIA',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - VITÓRIA',
    equipe_origem_s: 'EQUIPE PAGAMENTOS',
    nome_equipe_atual_s: 'EQUIPE PAGAMENTOS',
    codigo_act_s: '171.717.171',
    origem_act_s: 'PAGAMENTO',
    tema_act_s: '018',
    nome_tema_act_s: 'Comprovante DARF',
    tributo_act_s: 'IRPJ',
    act_s: '171',
    atividade_origem_s: 'Recebimento Pagamentos',
    assuntos_objetos_s: 'COMPROVANTE PAGAMENTO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc18',
    urlHcpSecundario_s: 'https://exemplo.com/doc18-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Comprovante anexado referente ao recolhimento de DARF...',
    nome_usuario_juntada_doc_s: 'Equipe Pagamentos',
    _version_: 1,
    score: 0.6
  },
  {
    id: '19',
    id_l: 19,
    processo_s: '14141.141421/2024-19',
    tipo_processo_s: 'RECURSO',
    subtipo_processo_s: 'ADMINISTRATIVO',
    grupo_processo_s: 'PROCESSO TRIBUTÁRIO',
    nome_arquivo_s: 'recurso_019.pdf',
    titulo_s: 'Recurso Administrativo - Impugnação',
    tipo_documento_s: 'RECURSO',
    situacao_s: 'EM JULGAMENTO',
    tamanho_l: 2750000,
    dt_juntada_tdt: '2024-09-30T13:20:00Z',
    dt_protocolo_tdt: '2024-09-28T09:00:00Z',
    dt_registro_tdt: '2024-09-30T13:25:00Z',
    dt_anexacao_tdt: '2024-09-29T14:00:00Z',
    atualizado_anexos_dt: '2024-09-30T13:25:00Z',
    nome_contribuinte_s: 'SERVIÇOS INDUSTRIAIS LTDA',
    ni_contribuinte_s: '16161616000122',
    cpf_responsavel_s: '16161616161',
    unidade_origem_s: 'CONSELHO ADMINISTRATIVO',
    nome_unidade_atual_s: 'CONSELHO ADMINISTRATIVO',
    equipe_origem_s: 'EQUIPE RECURSOS',
    nome_equipe_atual_s: 'EQUIPE RECURSOS',
    codigo_act_s: '181.818.181',
    origem_act_s: 'RECURSOS',
    tema_act_s: '019',
    nome_tema_act_s: 'Recurso Administrativo',
    tributo_act_s: 'IPI',
    act_s: '181',
    atividade_origem_s: 'Julgamento Recursos',
    assuntos_objetos_s: 'RECURSO IMPUGNAÇÃO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc19',
    urlHcpSecundario_s: 'https://exemplo.com/doc19-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Recurso administrativo contra lançamento de IPI...',
    nome_usuario_juntada_doc_s: 'Juiz Administrativo',
    _version_: 1,
    score: 2.5
  },
  {
    id: '20',
    id_l: 20,
    processo_s: '15151.271828/2023-20',
    tipo_processo_s: 'PRESTAÇÃO',
    subtipo_processo_s: 'RELATÓRIO MENSAL',
    grupo_processo_s: 'PROCESSO INTERNO',
    nome_arquivo_s: 'relatorio_mensal_020.pdf',
    titulo_s: 'Relatório Mensal - Unidade X',
    tipo_documento_s: 'RELATÓRIO',
    situacao_s: 'PUBLICADO',
    tamanho_l: 540000,
    dt_juntada_tdt: '2023-11-30T17:00:00Z',
    dt_protocolo_tdt: '2023-11-29T08:30:00Z',
    dt_registro_tdt: '2023-11-30T17:05:00Z',
    dt_anexacao_tdt: '2023-11-29T13:00:00Z',
    atualizado_anexos_dt: '2023-11-30T17:05:00Z',
    nome_contribuinte_s: 'UNIDADE X',
    ni_contribuinte_s: '17171717000133',
    cpf_responsavel_s: '17171717171',
    unidade_origem_s: 'UNIDADE X',
    nome_unidade_atual_s: 'UNIDADE X',
    equipe_origem_s: 'EQUIPE PRESTAÇÃO CONTAS',
    nome_equipe_atual_s: 'EQUIPE PRESTAÇÃO CONTAS',
    codigo_act_s: '191.919.191',
    origem_act_s: 'PRESTAÇÃO',
    tema_act_s: '020',
    nome_tema_act_s: 'Relatório Mensal',
    tributo_act_s: 'N/A',
    act_s: '191',
    atividade_origem_s: 'Prestação Contas',
    assuntos_objetos_s: 'RELATÓRIO MENSAL',
    urlHcpPrincipal_s: 'https://exemplo.com/doc20',
    urlHcpSecundario_s: 'https://exemplo.com/doc20-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'N',
    indicador_gerado_sistema_s: 'S',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Relatório mensal de atividades e indicadores...',
    nome_usuario_juntada_doc_s: 'Gerente Unidade',
    _version_: 1,
    score: 0.5
  },
  {
    id: '21',
    id_l: 21,
    processo_s: '16161.314159/2024-21',
    tipo_processo_s: 'REQUERIMENTO',
    subtipo_processo_s: 'ISENÇÃO',
    grupo_processo_s: 'PROCESSO TRIBUTÁRIO',
    nome_arquivo_s: 'requerimento_isencao_021.pdf',
    titulo_s: 'Pedido de Isenção - Tributo Municipal',
    tipo_documento_s: 'REQUERIMENTO',
    situacao_s: 'ANALISANDO DOCUMENTAÇÃO',
    tamanho_l: 620000,
    dt_juntada_tdt: '2024-02-14T10:20:00Z',
    dt_protocolo_tdt: '2024-02-12T09:00:00Z',
    dt_registro_tdt: '2024-02-14T10:25:00Z',
    dt_anexacao_tdt: '2024-02-13T15:40:00Z',
    atualizado_anexos_dt: '2024-02-14T10:25:00Z',
    nome_contribuinte_s: 'ONG AMIGA DA COMUNIDADE',
    ni_contribuinte_s: '18181818000144',
    cpf_responsavel_s: '18181818181',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - JOÃO PESSOA',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - JOÃO PESSOA',
    equipe_origem_s: 'EQUIPE ISENÇÃO',
    nome_equipe_atual_s: 'EQUIPE ISENÇÃO',
    codigo_act_s: '202.202.202',
    origem_act_s: 'ISENÇÃO',
    tema_act_s: '021',
    nome_tema_act_s: 'Pedido Isenção',
    tributo_act_s: 'ISS',
    act_s: '202',
    atividade_origem_s: 'Análise Isenções',
    assuntos_objetos_s: 'ISENÇÃO TRIBUTO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc21',
    urlHcpSecundario_s: 'https://exemplo.com/doc21-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Requerimento de isenção protocolado com documentação anexa...',
    nome_usuario_juntada_doc_s: 'Analista Isenção',
    _version_: 1,
    score: 1.7
  },
  {
    id: '22',
    id_l: 22,
    processo_s: '17171.271828/2024-22',
    tipo_processo_s: 'TERMO',
    subtipo_processo_s: 'TERMO DE INUTILIZAÇÃO',
    grupo_processo_s: 'PROCESSO ADMINISTRATIVO',
    nome_arquivo_s: 'termo_inutilizacao_022.pdf',
    titulo_s: 'Termo de Inutilização de Documento',
    tipo_documento_s: 'TERMO',
    situacao_s: 'EMITIDO',
    tamanho_l: 480000,
    dt_juntada_tdt: '2024-03-03T15:45:00Z',
    dt_protocolo_tdt: '2024-03-01T10:00:00Z',
    dt_registro_tdt: '2024-03-03T15:50:00Z',
    dt_anexacao_tdt: '2024-03-02T11:30:00Z',
    atualizado_anexos_dt: '2024-03-03T15:50:00Z',
    nome_contribuinte_s: 'ARQUIVO NACIONAL',
    ni_contribuinte_s: '19191919000155',
    cpf_responsavel_s: '19191919191',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - SÃO JOÃO',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - SÃO JOÃO',
    equipe_origem_s: 'EQUIPE ARQUIVO',
    nome_equipe_atual_s: 'EQUIPE ARQUIVO',
    codigo_act_s: '212.212.212',
    origem_act_s: 'ARQUIVO',
    tema_act_s: '022',
    nome_tema_act_s: 'Termo Inutilização',
    tributo_act_s: 'N/A',
    act_s: '212',
    atividade_origem_s: 'Inutilização Documentos',
    assuntos_objetos_s: 'TERMO INUTILIZAÇÃO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc22',
    urlHcpSecundario_s: 'https://exemplo.com/doc22-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'N',
    indicador_original_pesquisavel_s: 'N',
    indicador_gerado_sistema_s: 'S',
    arquivo_indexado_s: 'N',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Termo formalizando inutilização de documento antigo...',
    nome_usuario_juntada_doc_s: 'Arquivo Sistema',
    _version_: 1,
    score: 0.3
  },
  {
    id: '23',
    id_l: 23,
    processo_s: '18181.161803/2024-23',
    tipo_processo_s: 'PORTARIA',
    subtipo_processo_s: 'DESPACHO',
    grupo_processo_s: 'PROCESSO INTERNO',
    nome_arquivo_s: 'despacho_023.pdf',
    titulo_s: 'Despacho - Encaminhamento',
    tipo_documento_s: 'DESPACHO',
    situacao_s: 'EXPEDIDO',
    tamanho_l: 150000,
    dt_juntada_tdt: '2024-01-07T09:00:00Z',
    dt_protocolo_tdt: '2024-01-06T08:00:00Z',
    dt_registro_tdt: '2024-01-07T09:05:00Z',
    dt_anexacao_tdt: '2024-01-06T10:00:00Z',
    atualizado_anexos_dt: '2024-01-07T09:05:00Z',
    nome_contribuinte_s: 'DIRETORIA GERAL',
    ni_contribuinte_s: '20202020000166',
    cpf_responsavel_s: '20202020202',
    unidade_origem_s: 'DIRETORIA GERAL',
    nome_unidade_atual_s: 'DIRETORIA GERAL',
    equipe_origem_s: 'EQUIPE DESPACHOS',
    nome_equipe_atual_s: 'EQUIPE DESPACHOS',
    codigo_act_s: '222.222.222',
    origem_act_s: 'PORTARIA',
    tema_act_s: '023',
    nome_tema_act_s: 'Despacho Interno',
    tributo_act_s: 'N/A',
    act_s: '222',
    atividade_origem_s: 'Despachos',
    assuntos_objetos_s: 'DESPACHO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc23',
    urlHcpSecundario_s: 'https://exemplo.com/doc23-sec',
    indicador_sigilo_s: 'S',
    indicador_pesquisavel_s: 'N',
    indicador_original_pesquisavel_s: 'N',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'N',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Despacho interno encaminhando processo para análise...',
    nome_usuario_juntada_doc_s: 'Diretoria',
    _version_: 1,
    score: 0.4
  },
  {
    id: '24',
    id_l: 24,
    processo_s: '19191.314159/2024-24',
    tipo_processo_s: 'RELATÓRIO',
    subtipo_processo_s: 'ANÁLISE TÉCNICA',
    grupo_processo_s: 'PROCESSO TÉCNICO',
    nome_arquivo_s: 'analise_tecnica_024.pdf',
    titulo_s: 'Análise Técnica - Sistema Y',
    tipo_documento_s: 'RELATÓRIO TÉCNICO',
    situacao_s: 'EMITIDO',
    tamanho_l: 1250000,
    dt_juntada_tdt: '2024-05-20T10:00:00Z',
    dt_protocolo_tdt: '2024-05-18T09:00:00Z',
    dt_registro_tdt: '2024-05-20T10:05:00Z',
    dt_anexacao_tdt: '2024-05-19T15:00:00Z',
    atualizado_anexos_dt: '2024-05-20T10:05:00Z',
    nome_contribuinte_s: 'NÚCLEO TÉCNICO Y',
    ni_contribuinte_s: '21212121000177',
    cpf_responsavel_s: '21212121212',
    unidade_origem_s: 'NÚCLEO TÉCNICO',
    nome_unidade_atual_s: 'NÚCLEO TÉCNICO',
    equipe_origem_s: 'EQUIPE TÉCNICA',
    nome_equipe_atual_s: 'EQUIPE TÉCNICA',
    codigo_act_s: '232.323.232',
    origem_act_s: 'TÉCNICO',
    tema_act_s: '024',
    nome_tema_act_s: 'Análise Técnica',
    tributo_act_s: 'N/A',
    act_s: '232',
    atividade_origem_s: 'Análise',
    assuntos_objetos_s: 'ANÁLISE SISTEMA',
    urlHcpPrincipal_s: 'https://exemplo.com/doc24',
    urlHcpSecundario_s: 'https://exemplo.com/doc24-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'N',
    indicador_gerado_sistema_s: 'S',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Análise técnica do sistema com recomendações de segurança...',
    nome_usuario_juntada_doc_s: 'Analista Técnico',
    _version_: 1,
    score: 1.35
  },
  {
    id: '25',
    id_l: 25,
    processo_s: '20202.271828/2024-25',
    tipo_processo_s: 'TERMO',
    subtipo_processo_s: 'TERMO DE COMPROMISSO',
    grupo_processo_s: 'PROCESSO ADMINISTRATIVO',
    nome_arquivo_s: 'termo_compromisso_025.pdf',
    titulo_s: 'Termo de Compromisso - Parcelamento',
    tipo_documento_s: 'TERMO',
    situacao_s: 'ASSINADO',
    tamanho_l: 310000,
    dt_juntada_tdt: '2024-02-28T12:30:00Z',
    dt_protocolo_tdt: '2024-02-25T09:00:00Z',
    dt_registro_tdt: '2024-02-28T12:35:00Z',
    dt_anexacao_tdt: '2024-02-26T14:00:00Z',
    atualizado_anexos_dt: '2024-02-28T12:35:00Z',
    nome_contribuinte_s: 'EMPRESA PARCELA LTDA',
    ni_contribuinte_s: '22233344455566',
    cpf_responsavel_s: '22233344455',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - PETRÓPOLIS',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - PETRÓPOLIS',
    equipe_origem_s: 'EQUIPE NEGOCIAÇÃO',
    nome_equipe_atual_s: 'EQUIPE NEGOCIAÇÃO',
    codigo_act_s: '242.424.242',
    origem_act_s: 'PARCELAMENTO',
    tema_act_s: '025',
    nome_tema_act_s: 'Termo Compromisso',
    tributo_act_s: 'DIVERSOS',
    act_s: '242',
    atividade_origem_s: 'Negociação Dívida',
    assuntos_objetos_s: 'PARCELAMENTO TERMO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc25',
    urlHcpSecundario_s: 'https://exemplo.com/doc25-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Termo assinado referente ao parcelamento do débito...',
    nome_usuario_juntada_doc_s: 'Negociação Sistema',
    _version_: 1,
    score: 1.25
  },
  {
    id: '26',
    id_l: 26,
    processo_s: '21212.314159/2024-26',
    tipo_processo_s: 'MEMORANDO',
    subtipo_processo_s: 'INTERNO',
    grupo_processo_s: 'PROCESSO INTERNO',
    nome_arquivo_s: 'memorando_026.pdf',
    titulo_s: 'Memorando Interno - Comunicação',
    tipo_documento_s: 'MEMORANDO',
    situacao_s: 'LIDO',
    tamanho_l: 90000,
    dt_juntada_tdt: '2024-03-15T08:45:00Z',
    dt_protocolo_tdt: '2024-03-14T07:30:00Z',
    dt_registro_tdt: '2024-03-15T08:50:00Z',
    dt_anexacao_tdt: '2024-03-14T12:00:00Z',
    atualizado_anexos_dt: '2024-03-15T08:50:00Z',
    nome_contribuinte_s: 'SETOR RH',
    ni_contribuinte_s: '23232323000188',
    cpf_responsavel_s: '23232323232',
    unidade_origem_s: 'SETOR RH',
    nome_unidade_atual_s: 'SETOR RH',
    equipe_origem_s: 'EQUIPE RH',
    nome_equipe_atual_s: 'EQUIPE RH',
    codigo_act_s: '252.525.252',
    origem_act_s: 'MEMORANDO',
    tema_act_s: '026',
    nome_tema_act_s: 'Comunicação Interna',
    tributo_act_s: 'N/A',
    act_s: '252',
    atividade_origem_s: 'Comunicação',
    assuntos_objetos_s: 'MEMORANDO INTERNO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc26',
    urlHcpSecundario_s: 'https://exemplo.com/doc26-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'N',
    indicador_original_pesquisavel_s: 'N',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'N',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Memorando sobre procedimento interno de RH...',
    nome_usuario_juntada_doc_s: 'RH Sistema',
    _version_: 1,
    score: 0.1
  },
  {
    id: '27',
    id_l: 27,
    processo_s: '22222.271828/2024-27',
    tipo_processo_s: 'LAUDO',
    subtipo_processo_s: 'PERICIAL',
    grupo_processo_s: 'PROCESSO JUDICIAL',
    nome_arquivo_s: 'laudo_pericial_027.pdf',
    titulo_s: 'Laudo Pericial - Avaliação Técnica',
    tipo_documento_s: 'LAUDO',
    situacao_s: 'ENTREGUE',
    tamanho_l: 3500000,
    dt_juntada_tdt: '2024-06-18T10:40:00Z',
    dt_protocolo_tdt: '2024-06-16T09:00:00Z',
    dt_registro_tdt: '2024-06-18T10:45:00Z',
    dt_anexacao_tdt: '2024-06-17T14:00:00Z',
    atualizado_anexos_dt: '2024-06-18T10:45:00Z',
    nome_contribuinte_s: 'CIDADÃO EXEMPLO',
    ni_contribuinte_s: '24242424000199',
    cpf_responsavel_s: '24242424242',
    unidade_origem_s: 'PERÍCIA CENTRAL',
    nome_unidade_atual_s: 'PERÍCIA CENTRAL',
    equipe_origem_s: 'EQUIPE PERÍCIA',
    nome_equipe_atual_s: 'EQUIPE PERÍCIA',
    codigo_act_s: '262.626.262',
    origem_act_s: 'PERÍCIA',
    tema_act_s: '027',
    nome_tema_act_s: 'Laudo Pericial',
    tributo_act_s: 'N/A',
    act_s: '262',
    atividade_origem_s: 'Perícia',
    assuntos_objetos_s: 'LAUDO TÉCNICO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc27',
    urlHcpSecundario_s: 'https://exemplo.com/doc27-sec',
    indicador_sigilo_s: 'S',
    indicador_pesquisavel_s: 'N',
    indicador_original_pesquisavel_s: 'N',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'N',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Laudo contendo análise técnica pericial...',
    nome_usuario_juntada_doc_s: 'Perito Oficial',
    _version_: 1,
    score: 2.8
  },
  {
    id: '28',
    id_l: 28,
    processo_s: '23232.314159/2024-28',
    tipo_processo_s: 'MANIFESTAÇÃO',
    subtipo_processo_s: 'PARECER',
    grupo_processo_s: 'PROCESSO JURÍDICO',
    nome_arquivo_s: 'parecer_028.pdf',
    titulo_s: 'Parecer Jurídico - Análise Contratual',
    tipo_documento_s: 'PARECER',
    situacao_s: 'PRONTO',
    tamanho_l: 420000,
    dt_juntada_tdt: '2024-04-02T13:00:00Z',
    dt_protocolo_tdt: '2024-04-01T09:00:00Z',
    dt_registro_tdt: '2024-04-02T13:05:00Z',
    dt_anexacao_tdt: '2024-04-01T15:00:00Z',
    atualizado_anexos_dt: '2024-04-02T13:05:00Z',
    nome_contribuinte_s: 'DEPARTAMENTO JURÍDICO',
    ni_contribuinte_s: '25252525000111',
    cpf_responsavel_s: '25252525252',
    unidade_origem_s: 'ASSESSORIA JURÍDICA',
    nome_unidade_atual_s: 'ASSESSORIA JURÍDICA',
    equipe_origem_s: 'EQUIPE JURÍDICA',
    nome_equipe_atual_s: 'EQUIPE JURÍDICA',
    codigo_act_s: '272.727.272',
    origem_act_s: 'JURÍDICO',
    tema_act_s: '028',
    nome_tema_act_s: 'Parecer Jurídico',
    tributo_act_s: 'N/A',
    act_s: '272',
    atividade_origem_s: 'Pareceres',
    assuntos_objetos_s: 'PARECER CONTRATUAL',
    urlHcpPrincipal_s: 'https://exemplo.com/doc28',
    urlHcpSecundario_s: 'https://exemplo.com/doc28-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'N',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Parecer sobre cláusulas contratuais e riscos legais...',
    nome_usuario_juntada_doc_s: 'Advogado Chefe',
    _version_: 1,
    score: 1.7
  },
  {
    id: '29',
    id_l: 29,
    processo_s: '24242.271828/2024-29',
    tipo_processo_s: 'PROTOCOLO',
    subtipo_processo_s: 'REGISTRO',
    grupo_processo_s: 'PROCESSO ADMINISTRATIVO',
    nome_arquivo_s: 'protocolo_029.pdf',
    titulo_s: 'Comprovante de Protocolo - Registro',
    tipo_documento_s: 'PROTOCOLO',
    situacao_s: 'REGISTRADO',
    tamanho_l: 64000,
    dt_juntada_tdt: '2024-01-02T07:50:00Z',
    dt_protocolo_tdt: '2024-01-02T07:45:00Z',
    dt_registro_tdt: '2024-01-02T07:55:00Z',
    dt_anexacao_tdt: '2024-01-02T07:40:00Z',
    atualizado_anexos_dt: '2024-01-02T07:55:00Z',
    nome_contribuinte_s: 'CIDADÃO PROTOCOLADOR',
    ni_contribuinte_s: '26262626000155',
    cpf_responsavel_s: '26262626262',
    unidade_origem_s: 'PROTOCOLOS CENTRAIS',
    nome_unidade_atual_s: 'PROTOCOLOS CENTRAIS',
    equipe_origem_s: 'EQUIPE PROTOCOLOS',
    nome_equipe_atual_s: 'EQUIPE PROTOCOLOS',
    codigo_act_s: '282.828.282',
    origem_act_s: 'PROTOCOLO',
    tema_act_s: '029',
    nome_tema_act_s: 'Registro Protocolo',
    tributo_act_s: 'N/A',
    act_s: '282',
    atividade_origem_s: 'Registro',
    assuntos_objetos_s: 'PROTOCOLO REGISTRO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc29',
    urlHcpSecundario_s: 'https://exemplo.com/doc29-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'N',
    indicador_original_pesquisavel_s: 'N',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'N',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Comprovante emitido no ato do protocolo.',
    nome_usuario_juntada_doc_s: 'Atendente Protocolo',
    _version_: 1,
    score: 0.05
  },
  {
    id: '30',
    id_l: 30,
    processo_s: '25252.314159/2024-30',
    tipo_processo_s: 'INSTRUÇÃO',
    subtipo_processo_s: 'ANEXO',
    grupo_processo_s: 'PROCESSO TRIBUTÁRIO',
    nome_arquivo_s: 'instrucoes_030.pdf',
    titulo_s: 'Instruções de Procedimento - Atualização',
    tipo_documento_s: 'INSTRUÇÃO',
    situacao_s: 'VIGENTE',
    tamanho_l: 990000,
    dt_juntada_tdt: '2024-08-20T09:10:00Z',
    dt_protocolo_tdt: '2024-08-18T08:30:00Z',
    dt_registro_tdt: '2024-08-20T09:15:00Z',
    dt_anexacao_tdt: '2024-08-19T13:30:00Z',
    atualizado_anexos_dt: '2024-08-20T09:15:00Z',
    nome_contribuinte_s: 'COORDENAÇÃO NACIONAL',
    ni_contribuinte_s: '27272727000166',
    cpf_responsavel_s: '27272727272',
    unidade_origem_s: 'COORDENAÇÃO NACIONAL',
    nome_unidade_atual_s: 'COORDENAÇÃO NACIONAL',
    equipe_origem_s: 'EQUIPE NORMAS',
    nome_equipe_atual_s: 'EQUIPE NORMAS',
    codigo_act_s: '292.929.292',
    origem_act_s: 'NORMATIVA',
    tema_act_s: '030',
    nome_tema_act_s: 'Instruções Procedimentais',
    tributo_act_s: 'N/A',
    act_s: '292',
    atividade_origem_s: 'Normatização',
    assuntos_objetos_s: 'INSTRUÇÃO PROCEDIMENTO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc30',
    urlHcpSecundario_s: 'https://exemplo.com/doc30-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'N',
    indicador_gerado_sistema_s: 'S',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Atualização das instruções internas para procedimentos...',
    nome_usuario_juntada_doc_s: 'Chefia Normas',
    _version_: 2,
    score: 1.15
  }
];

export function generateFacetsFromDocuments(documents: Document[]): Record<string, Array<string | number>> {
  const grupoProcessoCounts: Record<string, number> = {};
  const tipoProcessoCounts: Record<string, number> = {};

  // Conta ocorrências
  documents.forEach(doc => {
    // Grupo Processo
    if (doc.grupo_processo_s) {
      grupoProcessoCounts[doc.grupo_processo_s] = (grupoProcessoCounts[doc.grupo_processo_s] || 0) + 1;
    }

    // Tipo Processo
    if (doc.tipo_processo_s) {
      tipoProcessoCounts[doc.tipo_processo_s] = (tipoProcessoCounts[doc.tipo_processo_s] || 0) + 1;
    }
  });

  // Converte para formato Solr: [nome, count, nome, count, ...]
  const grupoProcessoArray: Array<string | number> = [];
  Object.entries(grupoProcessoCounts)
    .sort((a, b) => b[1] - a[1]) // Ordena por count decrescente
    .forEach(([name, count]) => {
      grupoProcessoArray.push(name, count);
    });

  const tipoProcessoArray: Array<string | number> = [];
  Object.entries(tipoProcessoCounts)
    .sort((a, b) => b[1] - a[1])
    .forEach(([name, count]) => {
      tipoProcessoArray.push(name, count);
    });

  return {
    grupo_processo_s: grupoProcessoArray,
    tipo_processo_s: tipoProcessoArray
  };
}

// Facetas iniciais (de todos os documentos)
export const MOCK_FACETS = generateFacetsFromDocuments(MOCK_DOCUMENTS);