// src/services/mockData.ts

import type { Document } from '@/types/document.types';

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: '1',
    id_l: 1,
    processo_s: '10580.123456/2024-01',
    tipo_processo_s: 'LANÇAMENTO',
    subtipo_processo_s: 'AUTO DE INFRAÇÃO',
    grupo_processo_s: 'PROCESSO TRIBUTÁRIO',
    nome_arquivo_s: 'auto_infracao_001.pdf',
    titulo_s: 'Auto de Infração - IRPJ 2023',
    tipo_documento_s: 'AUTO DE INFRAÇÃO',
    situacao_s: 'JUNTADO',
    tamanho_l: 2048576,
    dt_juntada_tdt: '2024-01-15T10:30:00Z',
    dt_protocolo_tdt: '2024-01-10T14:20:00Z',
    dt_registro_tdt: '2024-01-15T10:35:00Z',
    dt_anexacao_tdt: '2024-01-14T16:45:00Z',
    atualizado_anexos_dt: '2024-01-15T10:35:00Z',
    nome_contribuinte_s: 'EMPRESA EXEMPLO LTDA',
    ni_contribuinte_s: '12345678000190',
    cpf_responsavel_s: '12345678901',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - SÃO PAULO',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - SÃO PAULO',
    equipe_origem_s: 'EQUIPE FISCALIZAÇÃO 01',
    nome_equipe_atual_s: 'EQUIPE FISCALIZAÇÃO 01',
    codigo_act_s: '123.456.789',
    origem_act_s: 'FISCALIZAÇÃO',
    tema_act_s: '001',
    nome_tema_act_s: 'IRPJ - Omissão de Receitas',
    tributo_act_s: 'IRPJ',
    act_s: '123',
    atividade_origem_s: 'Fiscalização IRPJ',
    assuntos_objetos_s: 'IRPJ OMISSÃO RECEITAS',
    urlHcpPrincipal_s: 'https://exemplo.com/doc1',
    urlHcpSecundario_s: 'https://exemplo.com/doc1-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Auto de infração referente ao exercício de 2023...',
    nome_usuario_juntada_doc_s: 'João Silva',
    _version_: 1,
    score: 1.5
  },
  {
    id: '2',
    id_l: 2,
    processo_s: '10580.789012/2024-02',
    tipo_processo_s: 'RESTITUIÇÃO',
    subtipo_processo_s: 'PEDIDO DE RESTITUIÇÃO',
    grupo_processo_s: 'PROCESSO TRIBUTÁRIO',
    nome_arquivo_s: 'pedido_restituicao_002.pdf',
    titulo_s: 'Pedido de Restituição - IRRF',
    tipo_documento_s: 'PETIÇÃO',
    situacao_s: 'JUNTADO',
    tamanho_l: 1024000,
    dt_juntada_tdt: '2024-02-20T09:15:00Z',
    dt_protocolo_tdt: '2024-02-18T11:00:00Z',
    dt_registro_tdt: '2024-02-20T09:20:00Z',
    dt_anexacao_tdt: '2024-02-19T15:30:00Z',
    atualizado_anexos_dt: '2024-02-20T09:20:00Z',
    nome_contribuinte_s: 'MARIA SANTOS',
    ni_contribuinte_s: '98765432000110',
    cpf_responsavel_s: '98765432100',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - RIO DE JANEIRO',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - RIO DE JANEIRO',
    equipe_origem_s: 'EQUIPE ATENDIMENTO 02',
    nome_equipe_atual_s: 'EQUIPE ATENDIMENTO 02',
    codigo_act_s: '987.654.321',
    origem_act_s: 'ATENDIMENTO',
    tema_act_s: '002',
    nome_tema_act_s: 'IRRF - Restituição',
    tributo_act_s: 'IRRF',
    act_s: '987',
    atividade_origem_s: 'Atendimento ao Contribuinte',
    assuntos_objetos_s: 'IRRF RESTITUIÇÃO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc2',
    urlHcpSecundario_s: 'https://exemplo.com/doc2-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Pedido de restituição de IRRF retido indevidamente...',
    nome_usuario_juntada_doc_s: 'Maria Oliveira',
    _version_: 1,
    score: 1.3
  },
  {
    id: '3',
    id_l: 3,
    processo_s: '10580.345678/2024-03',
    tipo_processo_s: 'RESSARCIMENTO',
    subtipo_processo_s: 'PEDIDO DE RESSARCIMENTO',
    grupo_processo_s: 'PROCESSO TRIBUTÁRIO',
    nome_arquivo_s: 'ressarcimento_003.pdf',
    titulo_s: 'Ressarcimento - PIS/COFINS',
    tipo_documento_s: 'REQUERIMENTO',
    situacao_s: 'EM ANÁLISE',
    tamanho_l: 3072000,
    dt_juntada_tdt: '2024-03-10T14:25:00Z',
    dt_protocolo_tdt: '2024-03-08T10:15:00Z',
    dt_registro_tdt: '2024-03-10T14:30:00Z',
    dt_anexacao_tdt: '2024-03-09T13:20:00Z',
    atualizado_anexos_dt: '2024-03-10T14:30:00Z',
    nome_contribuinte_s: 'INDÚSTRIA XYZ S.A.',
    ni_contribuinte_s: '11223344000155',
    cpf_responsavel_s: '11223344556',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - BRASÍLIA',
    nome_unidade_atual_s: 'DELEGACIA RECEITA FEDERAL - BRASÍLIA',
    equipe_origem_s: 'EQUIPE ANÁLISE 03',
    nome_equipe_atual_s: 'EQUIPE ANÁLISE 03',
    codigo_act_s: '111.222.333',
    origem_act_s: 'RESSARCIMENTO',
    tema_act_s: '003',
    nome_tema_act_s: 'PIS/COFINS - Ressarcimento',
    tributo_act_s: 'PIS/COFINS',
    act_s: '111',
    atividade_origem_s: 'Análise de Ressarcimento',
    assuntos_objetos_s: 'PIS COFINS RESSARCIMENTO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc3',
    urlHcpSecundario_s: 'https://exemplo.com/doc3-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Pedido de ressarcimento de créditos de PIS/COFINS...',
    nome_usuario_juntada_doc_s: 'Carlos Souza',
    _version_: 1,
    score: 1.8
  },
  {
    id: '4',
    id_l: 4,
    processo_s: '13031.567890/2023-04',
    tipo_processo_s: 'OUTROS PREVIDENCIÁRIO',
    subtipo_processo_s: 'CERTIDÃO',
    grupo_processo_s: 'PROCESSO PREVIDENCIÁRIO',
    nome_arquivo_s: 'certidao_previdenciaria.pdf',
    titulo_s: 'Certidão de Regularidade Previdenciária',
    tipo_documento_s: 'CERTIDÃO',
    situacao_s: 'DEFERIDO',
    tamanho_l: 512000,
    dt_juntada_tdt: '2023-12-05T08:45:00Z',
    dt_protocolo_tdt: '2023-12-01T09:30:00Z',
    dt_registro_tdt: '2023-12-05T08:50:00Z',
    dt_anexacao_tdt: '2023-12-04T16:00:00Z',
    atualizado_anexos_dt: '2023-12-05T08:50:00Z',
    nome_contribuinte_s: 'COMÉRCIO ABC LTDA',
    ni_contribuinte_s: '55667788000199',
    cpf_responsavel_s: '55667788990',
    unidade_origem_s: 'DELEGACIA RECEITA FEDERAL - BELO HORIZONTE',
    nome_unidade_atual_s: 'ARQUIVO ÚNICO',
    equipe_origem_s: 'EQUIPE CERTIDÕES',
    nome_equipe_atual_s: 'ARQUIVO ÚNICO',
    codigo_act_s: '444.555.666',
    origem_act_s: 'ATENDIMENTO',
    tema_act_s: '004',
    nome_tema_act_s: 'Certidão Previdenciária',
    tributo_act_s: 'CONTRIBUIÇÃO PREVIDENCIÁRIA',
    act_s: '444',
    atividade_origem_s: 'Emissão de Certidões',
    assuntos_objetos_s: 'CERTIDÃO PREVIDÊNCIA',
    urlHcpPrincipal_s: 'https://exemplo.com/doc4',
    urlHcpSecundario_s: 'https://exemplo.com/doc4-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'S',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Certidão de regularidade fiscal previdenciária...',
    nome_usuario_juntada_doc_s: 'Ana Paula',
    _version_: 1,
    score: 1.1
  },
  {
    id: '5',
    id_l: 5,
    processo_s: '16682.901234/2024-05',
    tipo_processo_s: 'AÇÃO JUDICIAL',
    subtipo_processo_s: 'MANDADO DE SEGURANÇA',
    grupo_processo_s: 'PROCESSO ADMINISTRATIVO',
    nome_arquivo_s: 'mandado_seguranca.pdf',
    titulo_s: 'Mandado de Segurança - Suspensão de Exigibilidade',
    tipo_documento_s: 'PETIÇÃO INICIAL',
    situacao_s: 'JUNTADO',
    tamanho_l: 4096000,
    dt_juntada_tdt: '2024-01-25T11:10:00Z',
    dt_protocolo_tdt: '2024-01-22T15:45:00Z',
    dt_registro_tdt: '2024-01-25T11:15:00Z',
    dt_anexacao_tdt: '2024-01-24T10:30:00Z',
    atualizado_anexos_dt: '2024-01-25T11:15:00Z',
    nome_contribuinte_s: 'CONSTRUTORA DELTA S.A.',
    ni_contribuinte_s: '99887766000144',
    cpf_responsavel_s: '99887766554',
    unidade_origem_s: 'PROCURADORIA GERAL DA FAZENDA NACIONAL',
    nome_unidade_atual_s: 'PROCURADORIA GERAL DA FAZENDA NACIONAL',
    equipe_origem_s: 'EQUIPE JURÍDICA 01',
    nome_equipe_atual_s: 'EQUIPE JURÍDICA 01',
    codigo_act_s: '777.888.999',
    origem_act_s: 'PGFN',
    tema_act_s: '005',
    nome_tema_act_s: 'Ações Judiciais',
    tributo_act_s: 'DIVERSOS',
    act_s: '777',
    atividade_origem_s: 'Contencioso Judicial',
    assuntos_objetos_s: 'MANDADO SEGURANÇA SUSPENSÃO',
    urlHcpPrincipal_s: 'https://exemplo.com/doc5',
    urlHcpSecundario_s: 'https://exemplo.com/doc5-sec',
    indicador_sigilo_s: 'N',
    indicador_pesquisavel_s: 'S',
    indicador_original_pesquisavel_s: 'S',
    indicador_gerado_sistema_s: 'N',
    arquivo_indexado_s: 'S',
    sem_conteudo_s: 'N',
    conteudo_txt: 'Mandado de segurança visando suspender exigibilidade...',
    nome_usuario_juntada_doc_s: 'Roberto Lima',
    _version_: 1,
    score: 2.1
  }
];

// Simula contagem de facetas
export const MOCK_FACETS = {
  grupo_processo_s: [
    'PROCESSO TRIBUTÁRIO', 3,
    'PROCESSO PREVIDENCIÁRIO', 1,
    'PROCESSO ADMINISTRATIVO', 1
  ],
  tipo_processo_s: [
    'LANÇAMENTO', 1,
    'RESTITUIÇÃO', 1,
    'RESSARCIMENTO', 1,
    'OUTROS PREVIDENCIÁRIO', 1,
    'AÇÃO JUDICIAL', 1
  ]
};